[project]
name = "mini-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "studyxiao", email = "studyxiao@163.com" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
